### ISSUE TITLE
POST requests return 403 when proxying locally to staging

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#135]
When developing locally on the frontend and proxying to https://dear-petition-staging.herokuapp.com/, ``POST`` requests fail:

```
2020-06-11T16:41:58.400638+00:00 heroku[router]: at=info method=POST path="/petition/api/token/" host=dear-petition-staging.herokuapp.com request_id=2e5d7840-7c25-4894-a00d-d7012d9c9520 fwd="127.0.0.1,71.70.229.1" dyno=web.1 connect=0ms service=67ms status=200 bytes=1031 protocol=https
2020-06-11T16:42:03.967550+00:00 heroku[router]: at=info method=POST path="/petition/api/batch/" host=dear-petition-staging.herokuapp.com request_id=afe4aa2b-5789-4d64-b828-d3233a34754a fwd="127.0.0.1,71.70.229.1" dyno=web.1 connect=1ms service=10ms status=403 bytes=475 protocol=https
```

Performing the same actions directly on staging work successfully.

**Comment by robert-w-gries** [comment]
I think [this setting](https://github.com/deardurham/dear-petition/blob/master/config/settings/base.py#L284-L287) is the problem. If we set it to `None` for staging it might start working

**Comment by robert-w-gries** [comment]
I've hit a similar issue locally where I get 403 errors while trying to log in or 500 errors while trying to generate the petition. I tried the above setting, and Django doesn't even allow the `None` value. It's likely a security concern so yeah what I said above is definitely not the solution.

I actually found I had to rebuild the container with `docker-compose build` in order to fix the issue. Not sure if something similar needs to happen with staging

**Comment by robert-w-gries** [comment]
It seems we might be able to fix this issue by using some of the settings listed in this question: https://stackoverflow.com/q/42201997

I noticed while trying to proxy from http://localhost:3000/admin to the staging url that there was an error message: `Referer checking failed - Referer is insecure while host is secure`

Before we can proxy from local frontend to staging backend, we need to somehow resolve this issue of http localhost.

**Comment by georgehelman** [comment]
I think this is fixed now.

**Comment by robert-w-gries** [comment]
It's not fixed, but it's not fixable as far as i know. It's a security issue of trying to retrieve info from a different domain. We almost certainly don't want to support it
